---
openapi: 3.0.0
info:
  title: Aptos Node Checker
  version: 0.1.0
servers:
  - url: "http://0.0.0.0:20121/api"
tags: []
paths:
  /check_node:
    get:
<<<<<<< HEAD
      summary: "Check the health of a given target node. You may specify a baseline node configuration to use for the evaluation. If you don't specify a baseline node configuration, we will attempt to determine the appropriate baseline based on your target node."
      parameters:
        - name: node_url
          schema:
            type: string
            format: url
          in: query
          description: "The URL of the node to check. e.g. http://44.238.19.217 or http://fullnode.mysite.com"
          required: true
          deprecated: false
        - name: baseline_configuration_name
          schema:
            type: string
          in: query
          description: "The name of the baseline node configuration to use for the evaluation, e.g. devnet_fullnode"
          required: false
          deprecated: false
        - name: metrics_port
          schema:
            type: integer
            format: uint16
            default: 9101
          in: query
          required: false
          deprecated: false
        - name: api_port
          schema:
            type: integer
            format: uint16
            default: 8080
          in: query
          required: false
          deprecated: false
        - name: noise_port
          schema:
            type: integer
            format: uint16
            default: 6180
          in: query
          required: false
          deprecated: false
=======
      summary: "Check the health of a given target node. You may sepcify a baseline node configuration\ntype to use for the evaluation. If you don't specify a baseline node configuration, we\nwill attempt to determine the appropriate baseline based on your target node."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckNodeRequest"
        required: true
>>>>>>> 0b1179325 (Update the openapi specs)
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationSummary"
  /check_preconfigured_node:
    get:
<<<<<<< HEAD
      summary: "Check the health of the preconfigured node. If none was specified when this instance of the node checker was started, this will return an error. You may specify a baseline node configuration to use for the evaluation. If you don't specify a baseline node configuration, we will attempt to determine the appropriate baseline based on your target node."
      parameters:
        - name: baseline_configuration_name
          schema:
            type: string
          in: query
          required: false
          deprecated: false
=======
      summary: "Check the health of the preconfigured node. If none was specified when the node health\nchecker was started, this will return an error."
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
>>>>>>> 0b1179325 (Update the openapi specs)
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationSummary"
components:
  schemas:
<<<<<<< HEAD
=======
    CheckNodeRequest:
      type: object
      required:
        - target_node
      properties:
        target_node:
          $ref: "#/components/schemas/NodeAddress"
        baseline_configuration_name:
          type: string
      example:
        target_node:
          url: "http://mynode.mysite.com/"
          metrics_port: 9101
          api_port: 8080
          noise_port: 6180
        baseline_configuration_name: Devnet Full Node
>>>>>>> 0b1179325 (Update the openapi specs)
    EvaluationResult:
      type: object
      required:
        - headline
        - score
        - explanation
        - source
        - links
      properties:
        headline:
          type: string
          description: "Headline of the evaluation, e.g. \"Healthy!\" or \"Metrics missing!\"."
        score:
          type: integer
          format: uint8
          description: Score out of 100.
        explanation:
          type: string
          description: Explanation of the evaluation.
        source:
          type: string
          description: "Name of the evaluator where the evaluation came from, e.g. state_sync."
        links:
          type: array
          description: Links that might help the user fix a potential problem.
          items:
            type: string
    EvaluationSummary:
<<<<<<< HEAD
=======
      type: object
      required:
        - evaluations
        - summary_score
        - summary_explanation
      properties:
        evaluations:
          type: array
          description: All the evaluations we ran.
          items:
            $ref: "#/components/schemas/EvaluationResult"
        summary_score:
          type: integer
          format: uint8
          description: An aggeregated summary (method TBA).
        summary_explanation:
          type: string
          description: An overall explanation of the results.
    NodeAddress:
>>>>>>> 0b1179325 (Update the openapi specs)
      type: object
      required:
        - evaluation_results
        - summary_score
        - summary_explanation
      properties:
        evaluation_results:
          type: array
          description: Results from all the evaluations NHC ran.
          items:
            $ref: "#/components/schemas/EvaluationResult"
        summary_score:
          type: integer
          format: uint8
          description: An aggeregated summary (method TBA).
        summary_explanation:
          type: string
<<<<<<< HEAD
          description: An overall explanation of the results.
=======
          format: url
          description: "Target URL. This should include a scheme (e.g. http://). If there is\nno scheme, we will prepend http://."
        metrics_port:
          type: integer
          format: uint16
          description: Metrics port.
          default: 9101
        api_port:
          type: integer
          format: uint16
          description: API port.
          default: 8080
        noise_port:
          type: integer
          format: uint16
          description: Validator communication port.
          default: 6180
      example:
        url: "http://mynode.mysite.com/"
        metrics_port: 9101
        api_port: 8080
        noise_port: 6180
>>>>>>> 0b1179325 (Update the openapi specs)
