/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{type: 'autogenerated', dirName: '.', }],
  aptosSidebar: [
    "intro",
    "guides/getting-started",
    {
      type: "category",
      label: "Quickstart Tutorials",
      collapsible: true,
      collapsed: true,
      items: [
        "tutorials/first-transaction",
        "tutorials/first-move-module",
        "tutorials/first-dapp",
        "tutorials/first-coin",
        "tutorials/your-first-nft",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsible: true,
      collapsed: true,
      items: [
        "basics/basics-txns-states",
        "basics/basics-accounts",
        "basics/basics-events",
        "basics/basics-gas-txn-fee",
        "basics/basics-merkle-proof",
        "basics/basics-fullnodes",
        "basics/basics-validator-nodes",
        "basics/basics-node-networks-sync",
      ],
    },
    
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: true,
      items: [
        "guides/basics-life-of-txn",
        "guides/sign-a-transaction",
        "guides/move",
        "guides/interfacing-with-the-blockchain",
        "tutorials/building-wallet-extension",
      ],
    },
    
    {
      type: "category",
      label: "Nodes",
      collapsible: true,
      collapsed: true,
      items: [
        "tutorials/local-testnet-devnet-incentivized-testnet",
        {
          type: "category",
          label: "Incentivized Testnet",
          collapsible: true,
          collapsed: true,
          items: [
            "tutorials/validator-node/intro",
            "reference/node-liveness-criteria",
            "tutorials/validator-node/connect-to-testnet",
          ],
        },
        {
          type: "category",
          label: "Install Node",
          collapsible: true,
          collapsed: true,
          items: [
            "tutorials/validator-node/using-aws",
            "tutorials/validator-node/using-azure",
            "tutorials/validator-node/using-gcp",
            "tutorials/validator-node/using-docker",
            "tutorials/validator-node/using-source-code",
            {
              type: "category",
              label: "FullNode for Devnet",
              collapsible: true,
              collapsed: true,
              items: [
                "tutorials/full-node/run-a-fullnode",
                "tutorials/full-node/update-fullnode-with-new-releases",
                "tutorials/full-node/network-identity-fullnode",
                "tutorials/full-node/troubleshooting-fullnode",
              ],
            },
            "tutorials/run-a-local-testnet",
            "tutorials/run-a-fullnode-on-gcp",
          ],
        },  
        "nodes/staking/staking-on-aptos",
      ],
    },
    {
      type: "category",
      label: "SDKs",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "link",
          label: "Typescript SDK",
          href: "https://aptos-labs.github.io/ts-sdk-doc/",            
        }
      ],
    },
    {
      type: "category",
      label: "APIs",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "link",
          label: "REST API",
          href: "/rest-api",            
        }
      ],
    },
    "reference/telemetry",
    "reference/glossary",
  ],
};

module.exports = sidebars;
